### ISSUE TITLE
Update to RC1-Final

### ISSUE THREAD

**Issue by sirkirby** [auth0/auth0-aspnetcore#4]
Hi @sandrinodimattia . Do you plan on updating the sample for the latest RC1 release? I've been trying to get things up and running on my own, but am running into some strange issues. Mainly, The site is simply rendering blank since I have every controller using an `[Authorize]` attribute. But no error, nothing to indicate an issue other than debugging it and watching the Events. I see the following events:

```
Event Type  Event   Time    Duration    Thread  Detail Description
Program Output  Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.Filters.AuthorizeFilter'.   2.26s       
```

```
Event Type  Event   Time    Duration    Thread  Detail Description
Program Output  Microsoft.AspNet.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes ().    2.26s       
```

```
Event Type  Event   Time    Duration    Thread  Detail Description
Program Output  Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request finished in 0ms 401   2.26s       
```

On Beta8, I would get the expected behavior of being redirected to my Account/Login page, but that does not happen. If I do manually navigate to that page, I get my Auth0 lock and am able to authenticate, but when it redirects back I just see the blank page again. I'm using the same setup as in this sample, with the minor tweaks to my configuration and the namespace and lib changes that were required when updating to the RC.

If there is anything I can provide from my setup that would help, I would be happy to provide additional details.

**Comment by christianlegault** [comment]
Hi. I'm having the same issue using RC1-Final.

**Comment by sandrinodm** [comment]
Samples have been updated to RC1 final.

**Comment by sirkirby** [comment]
Thanks!
