### ISSUE TITLE
app_metadata is not accessible in WebApp-OpenIdConnect-Sample.

### ISSUE THREAD

**Issue by abitofhelp** [auth0/auth0-aspnetcore#6]
Hello,

I added the following to the app_metadata of a user in our account at Auth0, and saved it.
{
  "tenantid": "123",
  "plans": [
    {
      "abcplan": {
        "roles": [
          "admin",
          "reports",
          "staff"
        ]
      }
    }
  ]
}

I set the following in the config.json file to our values:
  "Auth0": {
    "ClientId": "AAAAAA",
    "ClientSecret": "BBBBbbbbBBBBB",
    "Domain": "abcdef.auth0.com",
    "RedirectUri": "http://localhost:59383/"
  },

When I log in using Google, which is how the user is set at Auth0, I hit a breakpoint in ConfigureServices in Startup.cs.  When I look at the claims, I do not see the app_metadata items.  Can you please tell me what is wrong?

Thanks,

Mike

**Comment by sandrinodm** [comment]
Make sure you request that information in the `scope` when you show the Lock:

```
    lock.show({
        closable: false,
        callbackURL: window.location.origin + '/signin-oidc',
        authParams: {
            nonce: '@Model.Nonce',
            state: '@Model.State',
            scope: 'openid nickname email plans tenantid',
            response_type: 'code'
        }
    });
```

**Comment by abitofhelp** [comment]
Ahhh...  The sample did not indicate that I needed to add them to the scope; Now, I understand why they weren't there.  Thank you very much for your help and I hope that you will have a great holiday.
