### ISSUE TITLE
HS256 sample

### ISSUE THREAD

**Issue by dzolnjan** [auth0/auth0-aspnetcore#8]
Any chance of providing sample where tokens are singed with symmetric key HS256?

**Comment by jerriep** [comment]
We will start working on building out the ASP.NET Core examples sometime after RC2 has been released. 

For now you can refer to the OWIN example (https://github.com/auth0/auth0-aspnet-owin/tree/master/examples/WebApi). You will use a similar approach in ASP.NET Core using the JWT middleware.

HTH

**Comment by bragma** [comment]
Hi,
I am using HS256 with RC2 simply by configuring the middleware with a symmetric key using "SymmetricSecurityKey". Here are some parts of my code.

I am getting options from appsettings.json using this POCO object (but use whatever you want, this part is not important, I included it only to explain what follows):

```
public class Auth0Options
{
    public string Domain { get; set; }
    public string ClientId { get; set; }
    public bool SignedTokens { get; set; }
    public TimeSpan ClockSkew { get; set; }
    public bool ExpiringTokens { get; set; }
    public string SecurityKey { get; set; }
    public string ManagementToken { get; set; }
}
```

The in Startup.ch, I setup my services in this way (but again, some details may be changed):

```
// Configure Auth0
services.Configure<Auth0Options>(Configuration.GetSection("Auth:Auth0"));

// Setup policies
services.AddAuthorization(auth =>
{
    auth.AddPolicy("Auth0Bearer", new AuthorizationPolicyBuilder()
        .AddAuthenticationSchemes("Auth0")
        .RequireAuthenticatedUser()
        .RequireClaim(Auth0Token.ApiUserIdClaimType)
        .Build());
});
```

Lastly, in my Startup.cs' Configure method I call this:

```
private void ConfigureAuth0Tokens(IApplicationBuilder app, Auth0Options auth0Options)
{
    var securityKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(auth0Options.SecurityKey));

    app.UseJwtBearerAuthentication(new JwtBearerOptions
    {
        AutomaticAuthenticate = false,
        AuthenticationScheme = "Auth0",

        Audience = auth0Options.ClientId,
        Authority = $"https://{auth0Options.Domain}/",

        TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = auth0Options.SignedTokens,
            IssuerSigningKey = securityKey,

            // Validate the JWT Issuer (iss) claim
            ValidateIssuer = true,
            ValidIssuer = $"https://{auth0Options.Domain}/",

            // Validate the JWT Audience (aud) claim
            ValidateAudience = true,
            ValidAudience = auth0Options.ClientId,

            // Validate the token expiry and allow for some clock skew
            ValidateLifetime = auth0Options.ExpiringTokens,
            ClockSkew = auth0Options.ClockSkew,

            RequireSignedTokens = auth0Options.SignedTokens,
            RequireExpirationTime = auth0Options.ExpiringTokens
        }
    });
}
```

The most important detail here is the use of "SymmetricSecurityKey". I get my key from appsettings,json, passing it as a property of Auth0Options.
Notice that you the symmetric key MUST be set as Base64 encoded in Auth0's dashboard, while it must be in plaintext in your app. This took me some time to understand.

**Comment by jerriep** [comment]
Hi @bragma , that is correct. You can refer to our HS256 sample for this https://github.com/auth0-samples/auth0-aspnetcore-webapi-hs256
